# Generated by Django 5.0.4 on 2024-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0004_alter_artist_description'),
        ('Playlists', '0014_remove_playlist_artists_and_more'),
        ('Users', '0005_preferencelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencelist',
            name='artists',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='artists', to='Artists.artist'),
        ),
        migrations.AddField(
            model_name='preferencelist',
            name='playlists',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='playlists', to='Playlists.playlist'),
        ),
    ]
