# Generated by Django 5.0.4 on 2024-05-17 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0002_alter_playlist_genre_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 17, 13, 40, 13, 657034, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
