# Generated by Django 5.0.4 on 2024-05-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0004_remove_playlist_songs_playlist_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_thumbnail',
            field=models.ImageField(default='playlist_pics/album.png', upload_to='playlist_pics'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
