# Generated by Django 5.0.4 on 2024-05-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0002_alter_genre_genre_name'),
        ('Playlists', '0005_remove_playlist_image_playlist_playlist_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Genres.genre'),
        ),
    ]
