# Generated by Django 5.0.4 on 2024-05-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0002_alter_genre_genre_name'),
        ('Playlists', '0006_playlist_is_private_alter_playlist_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Genres.genre'),
        ),
    ]
