# Generated by Django 5.0.4 on 2024-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0008_alter_playlist_author_alter_playlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_thumbnail',
            field=models.ImageField(blank=True, default='playlist_pics/album.png', upload_to='playlist_pics'),
        ),
    ]
