# Generated by Django 5.0.4 on 2024-05-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0009_alter_playlist_playlist_thumbnail'),
        ('Songs', '0009_remove_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(default=None, to='Songs.song'),
        ),
    ]
