# Generated by Django 5.0.3 on 2024-05-18 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0002_artist_delete_playlist'),
        ('Playlists', '0010_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, to='Artists.artist'),
        ),
    ]
