# Generated by Django 5.0.3 on 2024-05-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0002_artist_delete_playlist'),
        ('Playlists', '0011_alter_playlist_author'),
        ('Users', '0005_preferencelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='artist',
            field=models.ManyToManyField(blank=True, to='Artists.artist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, to='Users.profile'),
        ),
    ]
