# Generated by Django 5.0.4 on 2024-05-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0012_playlist_artist_alter_playlist_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='artist',
            new_name='artists',
        ),
    ]
