# Generated by Django 5.0.4 on 2024-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0013_rename_artist_playlist_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='artists',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_thumbnail',
            field=models.ImageField(default='playlist_pics/album.png', upload_to='playlist_pics'),
        ),
    ]
