# Generated by Django 5.0.4 on 2024-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0007_friendrequest_delete_relationship'),
        ('Users', '0004_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='friends', to='Users.profile'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('send', 'send')], default='send', max_length=8),
        ),
    ]
