# Generated by Django 5.0.4 on 2024-05-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0011_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='send', max_length=8),
        ),
    ]
