# Generated by Django 5.0.3 on 2024-05-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0020_alter_friendrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('send', 'send'), ('rejected', 'rejected')], default='send', max_length=8),
        ),
    ]
