# Generated by Django 5.0.4 on 2024-05-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0004_song_lyrics_alter_song_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='song_name',
        ),
    ]
