# Generated by Django 5.0.4 on 2024-05-17 16:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Playlists', '0005_remove_playlist_image_playlist_playlist_thumbnail_and_more'),
        ('Songs', '0005_rename_title_song_song_name'),
        ('Users', '0004_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Playlists.playlist'),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, default=None, to='Users.profile'),
        ),
        migrations.AddField(
            model_name='song',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 17, 16, 54, 49, 258966, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='.jpg, .png, .jpeg, .gif, .svg supported', upload_to='audio_files/images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(help_text='.mp3 only supported', upload_to='audio_files'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=50),
        ),
    ]
