# Generated by Django 5.0.4 on 2024-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0006_remove_song_artist_remove_song_image_song_album_and_more'),
        ('Users', '0005_preferencelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(default=None, to='Users.profile'),
        ),
    ]
