# Generated by Django 5.0.4 on 2024-05-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0008_song_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
    ]
