# Generated by Django 5.0.3 on 2024-05-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0002_artist_delete_playlist'),
        ('Songs', '0009_remove_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(default=None, to='Artists.artist'),
        ),
    ]
