# Generated by Django 5.0.4 on 2024-05-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0011_alter_song_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(default='song_thumbnail/thumbnail.png', help_text='.jpg, .png, .jpeg, .gif, .svg supported', upload_to='song_thumbnail'),
        ),
    ]
