# Generated by Django 5.0.4 on 2024-05-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genres', '0003_remove_genre_genre_name_genre_name'),
        ('Songs', '0012_alter_song_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Genres.genre'),
        ),
    ]
