# Generated by Django 5.0.4 on 2024-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0003_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(default='no description...'),
        ),
    ]
